function Fanfic()
{
    return(<body className="article-background">
        <header className="articleTitle">A Retelling Of What Happened On The Day Of Gatsby's Death</header>
        <p>A strong stench of alcohol pervaded the room. Several bottles, some completely drained with only a licks worth of liquid left and yet others still half full and uncorked, were scattered across the floor, some flipped on their sides. One bottle with some liquid still in it lay at a sharp diagonal, little bits of substance oozing out slowly. Another bottle had even shattered in half, fragments of glass spilling out into an ugly mosaic reminiscent of modern art. In the center of this travesty was a luxurious couch. On it lay a fancily-dressed middle aged-man, sprawled out in an awkward position and snoring loudly. The stench of alcohol was strongest on his clothes, and clutched in his hand was a slip of paper, presumably the contact information of people he had met at a party the night before. His spectacles, vaguely resembling the eyes of an owl, lay by the side of the couch, seemingly tossed aside without a second thought. The clock on the wall struck noon. He had yet to stir.
</p>
        <p>A sudden knocking sound came from the front door, from down past the elegantly built set of stairs. The middle-aged man’s eyes snapped open. He grasped at the floor, searching panickedly for his owl-like glasses. Eventually, he found his glasses and donned them, before getting up and tottering his way out of the room and down the stairs. He opened the door and held it ajar, wincing at the bright sunlight that came through the doorway.
</p>
        <p>“Sir, the weekly paper.”</p>
        <p>“Oh joy, oh joy! Give it here, give it here!” The newspaper boy was visibly trying not to cringe from the smell of alcohol infused in the man’s breath.
</p>
        <p>Either still too drunk to notice or too excited to care, the middle-aged man grasped the newspaper. He briefly nodded his head in gratitude and shut the door. He walked back up the stairs, tottering slightly less than a few moments ago. He sat back down on the overly lavish couch and unfurled the newspaper. The big headline read “Behave Like an East Egg.” His gaze found the article and settled on it. As he traced the words, his eyes began to glaze over. He spat onto the floor, frustrated.
</p>
        <p>“Pretentious bastards.” His voice almost sounded self-deprecating.</p>
        <p>His gaze moved down past the main article, searching for something better. His eyes caught on a tiny segment in the very corner of the newspaper. The headline was tiny, as if it had intentionally been obscured from view. It read “The American Dream is Dead.” Despite having a bold, striking title full of controversy, the article itself barely contained any substance, as if parts of it had been removed, hollowed out or stripped away. Even the end of the article seemed to be missing something. The final line simply held a sentence beginning with “ The rich–” and abruptly ended off there, a sentence forever incompleted. Disappointed, the middle-aged man with owl-like glasses carelessly tossed the newspaper to the side, striking one of the many bottles of liquor lying on the floor. 
</p>
<p>Suddenly, he was struck with an odd yet terrible premonition. It was an unpleasant feeling–, a gut wrenching thought–, a foreboding suspicion. There was no proof whatsoever, but for some reason he felt absolutely certain. Certain of a certain man’s death. He hastily stood up and made his way out of his pigsty of a room and down the steps. Unlike before, his steps were firm and filled with certainty. He opened the front door and rushed into his automobile, getting onto the street and turning towards West Egg. Frightened at what might happen if he was too late, he pressed heavily on the pedal, increasingly panicked.</p>
<p>Right at the border of East Egg and West Egg, however, cars began to slow, making a long line and creating a seemingly uncrossable barrier. Though his destination was close, it felt like an unbreakable impasse, and undefeatable barrier. His heart clenched in dread as he unwillingly slowed the car down. He gazed around searching for the cause. A run-down, damaged gray car lay in a ditch off the roadside. Right next to the incident, there was a police officer speaking with the driver of a shiny red car. Just barely in view, he spotted an exchange of items between the driver and the officer, and, within a few moments, the road was clear. He raced towards West Egg.
</p>
<p>Finally making it to his destination, he quickly stopped his car  and opened the door. As he began to race up the steps, the sound of a gunshot resounded from off to the side at the pool. He felt his gut drop. His unfounded, dreadful suspicion turned into a dreadful conviction. He hurriedly changed directions, jumping down the steps off to the side. He forced his unsteady legs to move even faster, putting one after the other. Though his heart was pumping to keep up with his body, it felt constrained, restrained by this terrible, restrained feeling clawing at his throat. The swimming pool almost in sight, he raced against his near-overwhelming despair. </p>
<p>Another gunshot sounded out. The dreadful feeling–, the incredible despair–, the terrible conviction–All of it tightened its grip on him. He could hardly breathe. At last, he reached the pool.</p>
<p>He desperately searched the scene.</p>
<p>There was nothing there.</p>
<p>An illusion had vanished.</p>
<p>For some reason, the man felt hollow, as if a core part of him had been stripped away.</p>
<p>He stared, shocked, hollow, and desperate.</p>
    </body>);
}
export default Fanfic;